spring.datasource.url=jdbc:postgresql://ep-silent-union-amt63u7w-pooler.c-5.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dBu7EwRTb1CF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080